### ISSUE TITLE
how do run

### ISSUE THREAD

**Issue by jackIsAFat** [cuttooth/Daily-Programmer#1]
plz is halp

**Comment by jackIsAFat** [comment]
o no it virous broke copmpppoeoeottter plz to help[
wat is remoat acess plz is no

**Comment by jackIsAFat** [comment]
O̬̼͐̀͝h̨̛͚ͮͨͯ͆̋̎ͥͪͪ ͚̥̺͙͐͆̽ͦ̆̈̕͟m̢͇̖̮̹̰̞ͧ͗͌̊ͥͥ̀ͅa̷̵̠̱̺̖ͮ̊͆͜n̠͇͛̓̋͊͜͡͠ ̂̓̅̏͏͍̰̣̮̥͎͍͡I̶͖̼͔͓̅̎͆͂̀ ̥̟͂͌ͨ̒ͧͯ͟͠å̦̹̣͚̖̱͎͈̒ͦͮ͛m̧̦͚̺̺͎̞̪͉͖͑ͭ́ ̵ͧ̉͒̽̿͏̶͕̘̲̱͚n͉̈ͥ̍̄̆̕͜͠o̡̻͖̻͎̠͉̾͑ͦ̏̈̀͐ͩt̞̭͈̫̝̓̌̃͠ ̢̛̰̮̝̻͙̣̙̮ͭͥ̄ͬͫ̓ͭg̳̥͚͍̅̓̌̓͂̽̑ͅo̻̮̗̰̪̬̊̈́̓͘͝o͎̣͖̯̅ͤ̀̓ͣ̊ͭ͘͘͟d̛͙̞͖͎͛ͤͮ̔̑͡͞ ̶̧͚̝̝͙͎̭̖̏́̀ͅw͈͈͚̞ͬͮ̏̐͠i̶͕̹̠̳͎̦̟̣̠ͥ̐̍͞t̴̺͇͛ͮ̈ͫ͛͝ḩ̳̤̟͎̄ͯ̿̔̅͑ ̨͎̭̝̩͉̇ͪ͐̉̒̑͑c̡̟͇̱̺̈́̈ͪ̊o̖ͣ̇̀̏̀̚m̙̅́̄͛͠p͒ͪ͞҉̬͚̖̖͎̥ứ̠̜͉̹̹̗͗t͍̗̝̹̃ͨͭ̿̉̀͘ḙ̢̧̘̜́͘r͕̼̃š̷͉͕ͧ̊ͧ ͈ͫ̅Õ͉̺͔̩̯ͬh̭̮͎̗̓ͧ͗̿̃̆ͭ̚ ͍͕̜̼̋͌̑̓ͫ͂ͬ̾m̝̭̗͉͛̓̿͡a̲͍ͮ̑̒̈́ͮ̌ͫ̄͛́n̴̪͙͚̲̱ͭ͑̆͞ ̾ͨͣ̌ͤ҉̫̥̜̲̲͖I̴̭̝̘̼̫̳͇ͮ̔̀̅͑ͣ͡ͅ ̸̛͚̱̱̭̪͆́̍̊̇̾ͩą̹̹̄̒̍̅̒͂ͭ͌͜ṁ̴̵̢͔̖̏̄ͬ̐̍̂ͤ ̸̦͖̋̍̏̓̌ͣ͟ṋ̲͋̏̃̆ͧͩ͊́͜o͈̠̝͙͙̼̼͎͎͌̇ͤ̿ͬtͬ̒ͫͧ̅̍͑͒͂͏̝̻̗͈̱́ͅ ̜̠͊͛g̙̮ͬ̋͋͋͘͞ŏ̥͎̙͎̻̺̣̫͎̏̔̍ͥ͊̃͡o̴̯̜̬͑͐ͨͨͧ̾ď̸̡̜͍̯̌͛̐ͩͦͮͪ̆ͅͅ ̩̙̺͚͚̯͛͠w̗̠͙̪̲̜͕̦̃̀ͩ̄͑̎̓ͣ́́͜ï͚͎̭ͣͫ̅͂ͮ͆̓̕t͕͆̈͗̆̍ḥ̢̝̱̬̞͎͐ͧ́̑̓ͪ͛ ̧̩̰̎͠garlicc̗̳̄͢ŏ͙͕ͯ̌m͓̳ͭͦ̓̓ͧͭ̀͊ͮ͜ͅp̡͍̘͚̓ͤ̒̐u̝͓̘̥ͩ̐̍̅́̔̚͟t̵̙͙̝̐͂̌̀ͣ̕ē̴̥͔̦͉̼̯̃̄ͥ̇ͬr̵̡͍͎̗̻͉̙̤͔ͪͦ̌ͯͅş̮̻͉͓̬̗̮̥̬̔ͦ̂ͫ̒͟͢ ̢̧̨͖͉̦̼͎̔̎̀͋ͅȎ̢̒̒ͮ͂ͮ̉͐͏̭̤͍̞ͅh͕̖̞̩͈̺ͥ̄ͫ́͑͒̂ͯͅ ̭̠̮̬̰̺ͩ̽̊̊͐ͧ͝m̷͚͔̬̲̅͋ͫ͗ͩ̄̆a̡̻͍̰̳̝̮͖̬͂ͣ͗̃̓̾̀nͤ̃͗ͥͬͯ҉̤̯̠̰̯ ̵̧̰͔̮ͯ̂̔̿̇͌ͤI̵̘̰̗͖͕̟̎͊̒ͭͮ̂ͅ ̈̆̀̇͆ͣ͏̢͈͕́ͅa̒̽̾͌͞҉̻̻̝̰͓̱̙̱m̛͎͎̺̱̲̻͖ͩͣ͞ ̳͍̮̦̬̫̹̲͋͛͗ͪͩ̓̓͝n̴̗̟ͨ̀ͯ̚͢ǫ̶͔̪͇̱̝̥̘ͪͫ̔̇̅͐ͅt̏͌ͯ͆̍̅̈́̍͘҉͏̪̫ ͓̟̘̯͓̘͌̀̐̽ͦ̌͟g̵̣̮̬̹͓̺̀̾̀̐̄̔̅̚o̪͚̾̐̓ͩ̚ͅo̧͕̱̪̹͔ͤͨ̑̊̓ͥ͟d͙̥̳ͨ̌͌ͮ̚ ͙̟͕̼͖̹͈͎͖̓ẅ̤̯͉́̈́̍̈͋ͫͭ̕͞ḯ̡̥͍͈̙͙ͯ͒̈ͥ̃ͧt̰̩̾͐̆ͧ͂͗ͧ͜h̛̳̤̞̘͙ͦ̇ͪ̀ ̧̪̘̰̦̭ͥ̋c͉̥̄̀̚ȏ͈͈͚̫̊͒̍͋͂m̞̠͍̟͉̤̾̓͑̈ͨp̪͚͕̲̗͇͕͑͆̀ͅu̪ͪ͛͘t̹̰̮͗́̀ě͔̰͐͒ͧ̌͂͂ͦͤr̽͏̡̭̦͉̩͕̙͜ͅs̭͚̯͔̘̰̫̮̀͝ ̱̊̍͌̐̓ͫ͜ͅO̢̫͙͚̹̭̤͚̙͇͋̏̂͊̃̿͐̆́h̶̵̥̮̯̪͎͔̣̊ͬ͝ ͔̖̭̒͡m͉̳̞̙̂̌̄̈́ͩͬ̀ͯ͐ȧ̬͓̾̔̆ͦ̏͐n̴̹͕͙̙̤͇̞͆ͦ̿͗͑͢͢ ̨̥̖͚͚̹͈̒̽̈̊̓ͧ̓̔I̡̛̳̘͔̼ͩ ̢̲̙ͦͧ̊ͣ͋ȧ̴̮̹ͫ̃̓ͫ͞m̺̞̜̖͈͎͎̉̓͘ ̛̤̺͌͛̂̚n̶̝̭̥̬̱ͮͣͤͩ͑̓̅͒͞o̻̤̐͗ͮ͗͞t̻͖̫̩̱̙̩̞̰̒̾͆̉ͫ͌̚ ̥͉̺͑ͥ̐ͥͪ̊͟g̸̷̙͍̞̜͇͖̮̟̖͒ͩͮ̽̾o͓͖͌̎̅̓̀͜ͅo̜̦̰̘͚̖͍ͯ̈̌͜͝d̳̱̜͉͍̙̦̳̏ͣ̓͗̒̈́̚͘ ̷͇̄ͬͨ̿ͪͤͫ͟ẅ̳́̂ͣ͂͝i̼̭̝ͨ̓̀t͕̥̳̖̐̏̍ͧ̑̉͆͡h̛͕̭ͭ̓̐ͭͦ ̷͉͇͔͔̗͈͂͛ͩc̶̛͎̒͊o̤͔̻̒ͫ̓͆̔m̴̗̤̎͋ͦ͘p̨̝͈̣̱͇̭̟̠ͣǔ̵̧̲̻̪̬̖̣̣̰̹̃͛ͦͬ̔ͮ̀t̘̥̖̒̐͂͟e̢͍̳̺̬͍͐̄̾̈́͝rͫ̆ͦ̊ͬ͢҉̛̠̹̞s̴̢̫̦͕̘ͦ̃ͬͧͧͩ̄̎ ̶̬̋̈̀̓̽͒̈̓͟O̞̻̪̬̤̬͙ͣͬͦͪ͌͘͜h̭̝̝̼͐̐̏́̃̈̅̆͗ ̭̰̝̄̚͢m̡̠͇̅̔͋̚͟a̢͔͎̯͖ͤ̐̏̅ṅ̙͔̥̣̳ͣ̈ͥͫ̾ ̦͙͇̣͎̯̜͖͋͋ͥͮ͠Iͬ̐ͯ̎̔͏͖̤̞͍̟̖͠ ̴̷̣̱̼̥̬̱̺̆̈̌̊ą͔̝͚͋̓̃̓̍͑ͣ̈m̢͙̩̫͇̻͕ͦ̅̍̚͢͢ ̮̰̲̱͖̤̯̖̈́̿̎̂́̏ͪͮn͚̺̻̮̭̋ͩ͐͘o̔͂͐͏͝͏͔t̹̰͎̠͎͚̅͋́̚ ̴͖͖̮̔ͯͬ̔̊̚͠g̶̢̰̟̗͓̩̃̽̂ͅo̶͖̠̺̲͎̩̻͈͂̐̇͌ͤ̊ͣ̈̚ͅo͎͙̓̑ͭ͂̃̄͘d̞̩̳͓͚ͣ͌̈ͬ̇̒̒́̃͡͞ ̤͎̺͕̳̖̞̙̉ͪw͗̆̅ͦ͗ͯ̐҉̴̬̜̟̣͙̪͕̙͟ỉ̸̳̪̦̩̳̝ͯ̏̍̈̾͜ͅṯ̨̻̩̯̦̭̥͍͊́h̢̢̟̖̭̟͕͎̩̗͛̑́̐ ̴͎̥̲͇̦̞͕̾̔͡c̢͉̣̻̣̣̼̜͓ͪ̂̇ͨọ͇̺̖͔̫͉ͦ́m̰͈͊́ͯ͟p̡̻̼̹̻̹̙̯̩͛ͣͤͩ̆̈́̽ͫ́͠ù̲͔̞͈̥͙̐̑t̞ͣ̓͑ͨ̃́̇̈͡e̴̙̪̘̲͉̖̺͉̍ͪ̿̚r̤̽̊͠s̅̊̀̐͏̡͍̙͙͈̥̪̰͢garlic

**Comment by salfam** [comment]
test
